### ISSUE TITLE
How can i see my statements in the https://cloud.scorm.com/

### ISSUE THREAD

**Issue by allanzi** [RusticiSoftware/TinCanPHP#106]
Hello,

In trying to integrate with xApi, but i cant see the datas in the https://cloud.scorm.com/

Thanks

**Comment by brianjmiller** [comment]
There is a statement viewer for looking at statement data at https://cloud.scorm.com/sc/user/LRSView You will have to select the correct endpoint at the top under "View Statements In:" There is no UI for document viewing (yet, not planned). The Cloud LRS is generally expected to be accessed using the xAPI RESTful interface rather than the Cloud UI. If you need additional assistance with Cloud's LRS please email support@scorm.com

**Comment by brianjmiller** [comment]
Closing since this isn't really related to TinCanPHP. The Cloud support desk is very helpful.
