### ISSUE TITLE
Nice to have: $statement->verify could accept a URL as the publicKey

### ISSUE THREAD

**Issue by garemoko** [RusticiSoftware/TinCanPHP#25]
Workaround:
```
   $cert = openssl_pkey_get_public(openssl_x509_read(file_get_contents($certlocation)));

   $verifyResponse = $statement->verify(
       array(
           'publicKey' => $cert
       )
   );
```

**Comment by brianjmiller** [comment]
I have some concerns of making this too easy in the library because the public key really should be verified out of band to make sure it is the correct key. Pointing at a URL by itself is too susceptible to man-in-the-middle attacks. If a system wants to point at a URL for the contents of the key that is on them, and I think they should use the workaround as provided in that case. (Someone should feel free to re-open if they want to discuss it further.)
