### ISSUE TITLE
Update dependency namshi/jose to 7.1.*

### ISSUE THREAD

**Issue by sergey-rud** [RusticiSoftware/TinCanPHP#61]
Hello.

Can we update dependency **namshi/jose** to 7.1.* to be compatible with other packages as google/apiclient v2.*, etc?

**namshi/jose ~4.0** requires phpseclib/phpseclib ~0.3, but google/apiclient v2 requires ~2.0, so we have a conflict here.

**Comment by WillSkates** [comment]
sergey-rud: Can you submit a PR for this please?

**Comment by brianjmiller** [comment]
This is major version bump issue, and I'm holding on that until #47 lands, so this should be a pull request either against that branch and accepted there, or wait until that has landed then we can toss this in before cutting the major version release.

**Comment by xabbuh** [comment]
Doesn't it work if you simply allow both versions nd let the client decide which one to use?

**Comment by brianjmiller** [comment]
If the interfaces are sufficiently the same, yes, so long as we can specify the versions correctly in the `composer.json` such that it will satisfy the other dependencies.

**Comment by xabbuh** [comment]
[Tests pass](https://travis-ci.org/xabbuh/TinCanPHP/jobs/154548638) though I am not sure if that just happens because of no tests covering the differences of the library's versions.

**Comment by brianjmiller** [comment]
@xabbuh that shows a failure, for hhvm. though the failure looks like it may well be server side.

**Comment by brianjmiller** [comment]
The coverage for the signing stuff is actually pretty good, if the interface of theirs we use was broken I'd expect it to fail spectacularly. I'm not sure of the best way to proceed in that case, do we want to toss a bunch of `||` in there, a range?

**Comment by brianjmiller** [comment]
Bumping to 6.1.x which is where phpseclib 2.0 lands drops support for PHP 5.4 so this can't go in the 0.x release here.

The interesting thing is that going to 7.x means phpseclib is no longer a requirement at all and version should stop mattering since it is a suggestion anyways (as is openssl), and we require openssl. I don't know if PHPSecLib can satisfy all of our requirement for openssl because AFAIK it is used beyond the signature stuff in the HTTPS communication with LRSs. Does anyone know if phpseclib satsifies that requirement? At this point it would also be code changes to support phpseclib as the engine for the signature handling which I'm not overly inclined to take on at this moment and could be added in a minor version.

The only remaining question is we are at a major version bump point anyways, is it better to shed support for outdated versions of a library and require the latest going forwards, otherwise we leave ourselves having to support older versions or bump again to get rid of them.

**Comment by brianjmiller** [comment]
This would now land as part of #50, which bumps all dependencies to their latest.

**Comment by brianjmiller** [comment]
Released in 1.x.
