### ISSUE TITLE
Missing authentication header

### ISSUE THREAD

**Issue by savsofts** [RusticiSoftware/TinCanPHP#89]
I am sending username (scorm app id)  and password (secret key)  but returns "Missing authentication header"
here are sample code
```
$loader = require '../autoload.php';

$lrs = new TinCan\RemoteLRS(
    'https://cloud.scorm.com/tc/MGO0RPLGQQ/',
    '1.0.1',
    'MGO0RPLGQQ',
    'hwThBwz2naVgWxeiIT5EX61HA8Amr3OttL45jTkWw'
); 
echo "<pre>";
 $response = $lrs->queryStatements(['limit' => 2]);

 print_r($response);
```

**Comment by brianjmiller** [comment]
Not sure if you've already figured this out, because that App ID does not appear to be a valid SCORM Cloud App Id. If you didn't delete that App, then you should double check the App ID is correct. 

In general you should not provide the app id and certainly not secret key in a public forum such as this. For further assistance with Cloud, please contact support@scorm.com, no need to provide them with your secret key either, they can look it up based on the app id.
